runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /api/.*
  script: main.app

- url: /(.+)
  static_files: dist/\1
  upload: dist/(.*)

- url: /
  static_files: dist/index.html
  upload: dist/index.html

skip_files:
- ^node_modules$
- ^\.git$
- ^e2e$
- ^src$
- ^\..+$
- ^[a-z\.]+js$
- ^.+\.json$
